In [6]:
import pandas as pd

df = pd.read_csv('../ml/ml_dataset_cacao_ccn51.csv', sep=',')
df.sample(10)

,point_id,lat,lon,crop,period_start,period_end,label,month,biweek,mean_C,...,WRSI,deficit_pct,future_deficit_1m,future_deficit_3m,future_deficit_6m,future_deficit_1m_mm,future_deficit_3m_mm,future_deficit_6m_mm,suggestion,oni
24473,p113,5.259276,-76.559019,cacao_ccn51,2023-10-16,2023-10-31,2023-10_Q2,10,2,24.78,...,1.0000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,LOW,1.74
27540,p127,4.157300,-75.024850,cacao_ccn51,2023-11-01,2023-11-15,2023-11_Q1,11,1,24.57,...,1.0000,0.00,22.34,14.56,27.73,26.41,56.92,216.23,MEDIUM,1.90
45767,p210,1.816248,-76.836532,cacao_ccn51,2025-12-01,2025-12-15,2025-12_Q1,12,1,13.58,...,1.0000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,LOW,-0.60
17769,p083,5.966630,-74.595482,cacao_ccn51,2018-03-16,2018-03-31,2018-03_Q2,3,2,28.82,...,0.9214,7.86,0.00,0.00,0.00,0.00,0.00,0.00,LOW,-0.55
24006,p111,6.683996,-75.226641,cacao_ccn51,2022-08-01,2022-08-15,2022-08_Q1,8,1,18.87,...,1.0000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,LOW,-0.78
13505,p062,8.322696,-73.141127,cacao_ccn51,2023-01-16,2023-01-31,2023-01_Q2,1,2,17.38,...,1.0000,0.00,36.87,26.16,17.51,37.48,92.92,142.47,HIGH,-0.55
1512,p007,10.369265,-73.197079,cacao_ccn51,2025-03-16,2025-03-31,2025-03_Q2,3,2,24.30,...,0.1380,86.20,0.00,0.00,20.50,0.00,0.00,165.88,MEDIUM,-0.08
49564,p228,8.343690,-73.361794,cacao_ccn51,2019-11-16,2019-11-30,2019-11_Q2,11,2,19.86,...,1.0000,0.00,0.00,47.53,46.09,0.00,176.96,367.08,HIGH,0.72
611,p003,8.613147,-73.781791,cacao_ccn51,2024-03-01,2024-03-15,2024-03_Q1,3,1,29.53,...,0.2509,74.91,60.15,23.18,12.38,93.85,93.85,93.85,NOT_SUITABLE,1.18
51294,p236,8.420137,-73.308073,cacao_ccn51,2018-12-16,2018-12-31,2018-12_Q2,12,2,20.63,...,0.6570,34.30,89.26,82.68,42.82,112.95,321.62,335.14,NOT_SUITABLE,1.05

In [7]:
df_points = pd.read_csv('../ml/cacao_points.csv')
df_points.sample(5)

    point_id                  name        lat        lon          zone
64      p065       Saravena_Arauca   6.960000 -71.880000  intermediate
177     p178    Barrancas2_Guajira  11.038399 -72.852852           dry
171     p172      ElMolino_Guajira  10.538028 -72.946953           dry
220     p221            Cucuta_NdS   8.010179 -72.637009           dry
184     p185  Villanueva_Santander   6.711716 -73.283605           dry

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52341 entries, 0 to 52340
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   point_id              52341 non-null  object
 1   lat                   52341 non-null  float64
 2   lon                   52341 non-null  float64
 3   crop                  52341 non-null  object
 4   period_start          52341 non-null  object
 5   period_end            52341 non-null  object
 6   label                 52341 non-null  object
 7   month                 52341 non-null  int64
 8   biweek                52341 non-null  int64
 9   mean_C                52341 non-null  float64
 10  std_C                 52341 non-null  float64
 11  precip_total_mm       52341 non-null  float64
 12  precip_rainy_days     52341 non-null  float64
 13  pet_mm                52341 non-null  float64
 14  spei_1m               52341 non-null  float64
 15  spei_3m               52341 non-null  float64
 16  spei_6m               52341 non-null  float64
 17  spei_12m              52341 non-null  float64
 18  AWC_mm                52341 non-null  float64
 19  Storage_mm            52341 non-null  float64
 20  P_acum_mm             52341 non-null  float64
 21  WRSI                  52341 non-null  float64
 22  deficit_pct           52341 non-null  float64
 23  future_deficit_1m     52341 non-null  float64
 24  future_deficit_3m     52341 non-null  float64
 25  future_deficit_6m     52341 non-null  float64
 26  future_deficit_1m_mm  52341 non-null  float64
 27  future_deficit_3m_mm  52341 non-null  float64
 28  future_deficit_6m_mm  52341 non-null  float64
 29  suggestion            52341 non-null  object
 30  oni                   52341 non-null  float64
dtypes: float64(23), int64(2), object(6)
memory usage: 12.4+ MB

In [13]:
print(df.describe())

                lat           lon         month        biweek        mean_C  \
count  52341.000000  52341.000000  52341.000000  52341.000000  52341.000000
mean       6.116943    -74.192056      6.474886      1.502283     22.743836
std        2.703526      1.444258      3.488181      0.500000      4.069876
min        1.331277    -77.597932      1.000000      1.000000      7.970000
25%        3.707382    -75.118158      3.000000      1.000000     19.930000
50%        6.644307    -73.725318      6.000000      2.000000     23.570000
75%        8.091878    -73.161314     10.000000      2.000000     25.800000
max       11.176497    -70.182001     12.000000      2.000000     32.740000

              std_C  precip_total_mm  precip_rainy_days        pet_mm  \
count  52341.000000     52341.000000       52341.000000  52341.000000
mean       0.687163        89.306946           6.220286     51.775642
std        0.299206        77.562643           3.861279     18.077299
min        0.120000         0.000000           0.000000     21.150000
25%        0.470000        33.070000           3.000000     37.440000
50%        0.630000        71.660000           6.000000     48.350000
75%        0.830000       124.780000           9.000000     62.380000
max        2.820000       673.280000          16.000000    162.270000

            spei_1m  ...     P_acum_mm          WRSI   deficit_pct  \
count  52341.000000  ...  52341.000000  52341.000000  52341.000000
mean       0.064676  ...    172.287369      0.882035     11.796458
std        0.926602  ...    134.568319      0.243482     24.348178
min       -4.753000  ...      0.000000      0.000000      0.000000
25%       -0.652000  ...     75.560000      0.942500      0.000000
50%        0.072000  ...    144.250000      1.000000      0.000000
75%        0.774000  ...    232.160000      1.000000      5.750000
max        2.765000  ...   1261.620000      1.000000    100.000000

       future_deficit_1m  future_deficit_3m  future_deficit_6m  \
count       52341.000000       52341.000000       52341.000000
mean           11.889205          12.119462          12.468104
std            24.446058          19.716936          15.392510
min             0.000000           0.000000           0.000000
25%             0.000000           0.000000           0.000000
50%             0.000000           0.000000           5.670000
75%             6.210000          18.710000          21.930000
max           100.000000         100.000000          88.840000

       future_deficit_1m_mm  future_deficit_3m_mm  future_deficit_6m_mm  \
count          52341.000000          52341.000000          52341.000000
mean              15.915931             47.607452             95.724012
std               33.251144             78.876203            119.910564
min                0.000000              0.000000              0.000000
25%                0.000000              0.000000              0.000000
50%                0.000000              0.000000             41.780000
75%                8.010000             71.240000            165.880000
max              205.950000            515.750000            668.520000

                oni
count  52341.000000
mean      -0.001872
std        0.724267
min       -1.110000
25%       -0.610000
50%       -0.110000
75%        0.460000
max        1.990000

[8 rows x 25 columns]

In [15]:
print(df[['AWC_mm','P_acum_mm','Storage_mm']].describe())

             AWC_mm     P_acum_mm    Storage_mm
count  52341.000000  52341.000000  52341.000000
mean     136.158619    172.287369     79.615486
std        7.713359    134.568319     57.530122
min      116.600000      0.000000      0.000000
25%      132.050000     75.560000     12.150000
50%      134.770000    144.250000     94.450000
75%      139.310000    232.160000    133.400000
max      181.280000   1261.620000    181.280000

In [9]:
count = df['suggestion'].value_counts()
percent = count / len(df) * 100
total = pd.DataFrame({
    'category': count,
    'percent': percent
})
print(total)

              category    percent
suggestion
LOW              29723  56.787222
MEDIUM            7670  14.653904
NOT_SUITABLE      7552  14.428460
HIGH              7396  14.130414

In [10]:
print(df[['deficit_pct', 'future_deficit_1m', 'future_deficit_3m','future_deficit_6m']].describe())

        deficit_pct  future_deficit_1m  future_deficit_3m  future_deficit_6m
count  52341.000000       52341.000000       52341.000000       52341.000000
mean      11.796458          11.889205          12.119462          12.468104
std       24.348178          24.446058          19.716936          15.392510
min        0.000000           0.000000           0.000000           0.000000
25%        0.000000           0.000000           0.000000           0.000000
50%        0.000000           0.000000           0.000000           5.670000
75%        5.750000           6.210000          18.710000          21.930000
max      100.000000         100.000000         100.000000          88.840000

In [11]:
df['point_id'].value_counts()

point_id
p001    219
p002    219
p003    219
p004    219
p005    219
       ...
p236    219
p237    219
p238    219
p239    219
p240    219
Name: count, Length: 239, dtype: int64